spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/ewm_stats_db
    username: stat_user
    password: stat_password

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: stats_analyzer
  sql:
    init:
      mode: always

kafka:
  bootstrap:
    servers: localhost:9092
  consumer:
    group:
      action: stats.analyzer.action
      similarity: stats.analyzer.similarity
    poll:
      timeout: 100
  topics:
    stats-user-action-v1: stats.user-actions.v1
    stats-events-similarity-v1: stats.events-similarity.v1

grpc:
  server:
    port: 0